export const MY_LOCATION ='MY_LOCATION';
export const WEATHER ='WEATHER';
export const QUOTE ='QUOTE';
export const ADD_TO_LOCALSTORAGE= 'ADD_TO_LOCALSTORAGE';
export const DISPLAY_LOCALSTORAGE_DATA ='DISPLAY_LOCALSTORAGE_DATA';
export const REMOVE_FROM_LOCALSTORAGE='REMOVE_FROM_LOCALSTORAGE';
export const GEO_ERROR='GEO_ERROR';
export const  FETCHING_ERROR = 'FETCHING_ERROR';